export const DASHBOARD = {
    GET_INITIAL_DATA: 'GET_INITIAL_DATA',
    SEND_INITAIL_DATA: 'SEND_INITAIL_DATA',
    APPROVE_AS_MEMBER: 'APPROVE_AS_MEMBER',
    APPROVED_AS_MEMBER: 'APPROVED_AS_MEMBER',
};