export const ATTENDANCE = {
    ATTENDANCE_GET_CLASSES_LIST: 'ATTENDANCE_GET_CLASSES_LIST',
    ATTENDANCE_SEND_CLASSES_LIST: 'ATTENDANCE_SEND_CLASSES_LIST',

    REQUEST_CLASS_STUDENT_ATTENDANCE: 'REQUEST_CLASS_STUDENT_ATTENDANCE',
    SEND_CLASS_STUDENT_ATTENDANCE: 'SEND_CLASS_STUDENT_ATTENDANCE',

    REQUEST_CURRENT_ATTENDANCE: 'REQUEST_CURRENT_ATTENDANCE',
    SEND_CURRENT_ATTENDANCE: 'SEND_CURRENT_ATTENDANCE',

    SUBMIT_ATTENDANCE: 'SUBMIT_ATTENDANCE',

    ATTENDANCE_SEND_LOADING: 'ATTENDANCE_SEND_LOADING'

};