export const MEMBERSHIP = {
    SEND_MEMBERSHIP_DATA: 'SEND_MEMBERSHIP_DATA',
    SEND_MEMBERSHIP_DATA_SUCCESS: 'SEND_MEMBERSHIP_DATA_SUCCESS',
    PAY_MEMBERSHIP_FEE: 'PAY_MEMBERSHIP_FEE',
    PAY_MEMBERSHIP_FEE_SUCCESS: 'PAY_MEMBERSHIP_FEE_SUCCESS',

};