export const PLAYERCLASS = {
    GET_PLAYER_CLASSES_LIST: 'GET_PLAYER_CLASSES_LIST',
    SEND_PLAYER_CLASSES_LIST: 'SEND_PLAYER_CLASSES_LIST',

    REQUEST_CLASS_UPDATE: 'REQUEST_CLASS_UPDATE',
    SEND_CLASS_UPDATE_SUCCESS: 'SEND_CLASS_UPDATE_SUCCESS',

    REQUEST_CLASS_DELETE: 'REQUEST_CLASS_DELETE',
    SEND_CLASS_DELETE_SUCCESS: 'SEND_CLASS_DELETE_SUCCESS',

    REQUEST_CLASS_PAYMENT: 'REQUEST_CLASS_PAYMENT',
    GOTO_PLAYER_CLASS_PAYMENT: 'GOTO_PLAYER_CLASS_PAYMENT',

    REQUEST_PLAYER_CHECKOUT: 'REQUEST_PLAYER_CHECKOUT',

    SEND_LOADING: 'SEND_LOADING'

};