export const CLASS = {
    GET_CLASSES_LIST: 'GET_CLASSES_LIST',
    SEND_CLASSES_LIST: 'SEND_CLASSES_LIST',

    REQUEST_NEW_CLASS_CREATE: 'REQUEST_NEW_CLASS_CREATE',
    SEND_CLASS_CREATE_SUCCESS: 'SEND_CLASS_CREATE_SUCCESS',

    REQUEST_CLASS_UPDATE: 'REQUEST_CLASS_UPDATE',
    SEND_CLASS_UPDATE_SUCCESS: 'SEND_CLASS_UPDATE_SUCCESS',

    REQUEST_CLASS_DELETE: 'REQUEST_CLASS_DELETE',
    SEND_CLASS_DELETE_SUCCESS: 'SEND_CLASS_DELETE_SUCCESS',

    REQUEST_CLASS_DETAIL: 'REQUEST_CLASS_DETAIL',
    SEND_CLASS_DETAIL: 'SEND_CLASS_DETAIL',

    REQUEST_CLASS_CREATE_ROUTE: 'REQUEST_CLASS_CREATE_ROUTE',
    SEND_CLASS_CREATE_ROUTE: 'SEND_CLASS_CREATE_ROUTE',

    SEND_LOADING: 'SEND_LOADING'

};