export const TEACHER_CLASS = {
    TEACHER_GET_CLASSES_LIST: 'TEACHER_GET_CLASSES_LIST',
    TEACHER_SEND_CLASSES_LIST: 'TEACHER_SEND_CLASSES_LIST',

    TEACHER_REQUEST_CLASS_DETAIL: 'TEACHER_REQUEST_CLASS_DETAIL',
    TEACHER_SEND_CLASS_DETAIL: 'TEACHER_SEND_CLASS_DETAIL',

    TEACHER_SEND_LOADING: 'TEACHER_SEND_LOADING'

};