export const PLAYERS = {
    GET_PLAYERS_LIST: 'GET_PLAYERS_LIST',
    SEND_PLAYERS_LIST: 'SEND_PLAYERS_LIST',

    REQUEST_PLAYER_UPDATE: 'REQUEST_PLAYER_UPDATE',
    SEND_PLAYER_UPDATE_SUCCESS: 'SEND_PLAYER_UPDATE_SUCCESS',

    REQUEST_PLAYER_APPROVE: 'REQUEST_PLAYER_APPROVE',

    REQUEST_PLAYER_DELETE: 'REQUEST_PLAYER_DELETE',
    SEND_PLAYER_DELETE_SUCCESS: 'SEND_PLAYER_DELETE_SUCCESS',

    REQUEST_PLAYER_DETAIL: 'REQUEST_PLAYER_DETAIL',
    SEND_PLAYER_DETAIL: 'SEND_PLAYER_DETAIL',

    SEND_LOADING: 'SEND_LOADING'

};