export const KID = {
    GET_KIDS_LIST: 'GET_KIDS_LIST',
    SEND_KIDS_LIST: 'SEND_KIDS_LIST',

    REQUEST_NEW_KID_CREATE: 'REQUEST_NEW_KID_CREATE',

    REQUEST_KID_CLASS_LIST: 'REQUEST_KID_CLASS_LIST',
    SEND_KID_CLASSES_LIST: 'SEND_KID_CLASSES_LIST',

    REQUEST_KID_UPDATE: 'REQUEST_KID_UPDATE',
    SEND_KID_UPDATE_SUCCESS: 'SEND_KID_UPDATE_SUCCESS',

    REQUEST_KID_DELETE: 'REQUEST_KID_DELETE',
    SEND_KID_DELETE_SUCCESS: 'SEND_KID_DELETE_SUCCESS',

    REQUEST_KID_DETAIL: 'REQUEST_KID_DETAIL',
    SEND_KID_DETAIL: 'SEND_KID_DETAIL',

    REQUEST_NEW_KID_CONTACT_CREATE: 'REQUEST_NEW_KID_CONTACT_CREATE',
    SEND_KID_CREATE_CONTACT_SUCCESS: 'SEND_KID_CREATE_CONTACT_SUCCESS',
    
    REQUEST_KID_CONTACT_DETAIL: 'REQUEST_KID_CONTACT_DETAIL',
    SEND_KID_CONTACT_DETAIL: 'SEND_KID_CONTACT_DETAIL',
    GOTO_KID_CONTACT_DETAIL: 'GOTO_KID_CONTACT_DETAIL',

    REQUEST_KID_CONTACT_UPDATE: 'REQUEST_KID_CONTACT_UPDATE',
    REQUEST_KID_CONTACT_DELETE: 'REQUEST_KID_CONTACT_DELETE',

    GOTO_KID_PAYMENT: 'GOTO_KID_PAYMENT', 
    REQUEST_KID_PAYMENT: 'REQUEST_KID_PAYMENT', 
    REQUEST_NEW_KID_PAYMENT: 'REQUEST_NEW_KID_PAYMENT', 
    REQUEST_KID_PAYMENT_UPDATE: 'REQUEST_KID_PAYMENT_UPDATE', 
    REQUEST_KID_PAYMENT_DELETE: 'REQUEST_KID_PAYMENT_DELETE', 
    SEND_KID_PAYMENT: 'SEND_KID_PAYMENT', 

    SEND_CHECKOUT:  'SEND_CHECKOUT',
    SEND_PAYMENT_OPTION: 'SEND_PAYMENT_OPTION',

    GOTO_DETAIL: 'GOTO_DETAIL',
    BACK_GOTO_DETAIL: 'BACK_GOTO_DETAIL',

    REQUEST_ATTENDANCE_HISTORY: 'REQUEST_ATTENDANCE_HISTORY',
    SEND_ATTENDANCE_HISTORY: 'SEND_ATTENDANCE_HISTORY',
    REQUEST_ATTENDANCE_CLASSES: 'REQUEST_ATTENDANCE_CLASSES',
    SEND_ATTENDANCE_CLASSES: 'SEND_ATTENDANCE_CLASSES',

    GOTO_KID_EVENTS: 'GOTO_KID_EVENTS',
    SEND_KID_EVENTS: 'SEND_KID_EVENTS',

    SEND_LOADING: 'SEND_LOADING'
};