export const PROFILE = {

    REQUEST_ACCOUNT_UPDATE: 'REQUEST_ACCOUNT_UPDATE',
    SEND_ACCOUNT_UPDATE_SUCCESS: 'SEND_ACCOUNT_UPDATE_SUCCESS',
    
    REQUEST_CARD_UPDATE: 'REQUEST_CARD_UPDATE',
    SEND_CARD_UPDATE_SUCCESS: 'SEND_CARD_UPDATE_SUCCESS',

    REQUEST_BANK_UPDATE: 'REQUEST_BANK_UPDATE',
    SEND_BANK_UPDATE_SUCCESS: 'SEND_BANK_UPDATE_SUCCESS',

    REQUEST_PROFILE_DETAIL: 'REQUEST_PROFILE_DETAIL',
    SEND_PROFILE_DETAIL: 'SEND_PROFILE_DETAIL',
};