export const STUDENT = {
    GET_STUDENTS_LIST: 'GET_STUDENTS_LIST',
    SEND_STUDENTS_LIST: 'SEND_STUDENTS_LIST',

    REQUEST_CLASS_LIST: 'REQUEST_CLASS_LIST',
    SEND_CLASSES_LIST: 'SEND_CLASSES_LIST',

    REQUEST_NEW_STUDENT_CREATE: 'REQUEST_NEW_STUDENT_CREATE',
    SEND_STUDENT_CREATE_SUCCESS: 'SEND_STUDENT_CREATE_SUCCESS',

    REQUEST_STUDENT_UPDATE: 'REQUEST_STUDENT_UPDATE',
    SEND_STUDENT_UPDATE_SUCCESS: 'SEND_STUDENT_UPDATE_SUCCESS',

    REQUEST_STUDENT_DELETE: 'REQUEST_STUDENT_DELETE',
    SEND_STUDENT_DELETE_SUCCESS: 'SEND_STUDENT_DELETE_SUCCESS',

    REQUEST_STUDENT_DETAIL: 'REQUEST_STUDENT_DETAIL',
    SEND_STUDENT_DETAIL: 'SEND_STUDENT_DETAIL',

    REQUEST_NEW_STUDENT_CONTACT_CREATE: 'REQUEST_NEW_STUDENT_CONTACT_CREATE',
    SEND_STUDENT_CREATE_CONTACT_SUCCESS: 'SEND_STUDENT_CREATE_CONTACT_SUCCESS',
    
    REQUEST_STUDENT_CONTACT_DETAIL: 'REQUEST_STUDENT_CONTACT_DETAIL',
    SEND_STUDENT_CONTACT_DETAIL: 'SEND_STUDENT_CONTACT_DETAIL',
    GOTO_STUDENT_CONTACT_DETAIL: 'GOTO_STUDENT_CONTACT_DETAIL',

    REQUEST_STUDENT_CONTACT_UPDATE: 'REQUEST_STUDENT_CONTACT_UPDATE',
    REQUEST_STUDENT_CONTACT_DELETE: 'REQUEST_STUDENT_CONTACT_DELETE',

    GOTO_STUDENT_PAYMENT: 'GOTO_STUDENT_PAYMENT', 
    REQUEST_STUDENT_PAYMENT: 'REQUEST_STUDENT_PAYMENT', 
    REQUEST_NEW_STUDENT_PAYMENT: 'REQUEST_NEW_STUDENT_PAYMENT', 
    REQUEST_STUDENT_PAYMENT_UPDATE: 'REQUEST_STUDENT_PAYMENT_UPDATE', 
    REQUEST_STUDENT_PAYMENT_DELETE: 'REQUEST_STUDENT_PAYMENT_DELETE', 
    SEND_STUDENT_PAYMENT: 'SEND_STUDENT_PAYMENT', 

    SEND_CHECKOUT:  'SEND_CHECKOUT',
    SEND_PAYMENT_OPTION: 'SEND_PAYMENT_OPTION',

    GOTO_DETAIL: 'GOTO_DETAIL',
    BACK_GOTO_DETAIL: 'BACK_GOTO_DETAIL',

    REQUEST_ATTENDANCE_HISTORY: 'REQUEST_ATTENDANCE_HISTORY',
    SEND_ATTENDANCE_HISTORY: 'SEND_ATTENDANCE_HISTORY',
    REQUEST_ATTENDANCE_CLASSES: 'REQUEST_ATTENDANCE_CLASSES',
    SEND_ATTENDANCE_CLASSES: 'SEND_ATTENDANCE_CLASSES',

    SAVE_ATTENDANCE: 'SAVE_ATTENDANCE',
    SAVE_MAKEUP_ATTENDANCE: 'SAVE_MAKEUP_ATTENDANCE',

    SEND_LOADING: 'SEND_LOADING'
};