export const COACHES = {
    GET_COACHES_LIST: 'GET_COACHES_LIST',
    SEND_COACHES_LIST: 'SEND_COACHES_LIST',

    REQUEST_NEW_COACHE_CREATE: 'REQUEST_NEW_COACHE_CREATE',
    SEND_COACHE_CREATE_SUCCESS: 'SEND_COACHE_CREATE_SUCCESS',

    REQUEST_COACHE_UPDATE: 'REQUEST_COACHE_UPDATE',
    SEND_COACHE_UPDATE_SUCCESS: 'SEND_COACHE_UPDATE_SUCCESS',

    REQUEST_COACHE_DELETE: 'REQUEST_COACHE_DELETE',
    SEND_COACHE_DELETE_SUCCESS: 'SEND_COACHE_DELETE_SUCCESS',

    REQUEST_COACHE_DETAIL: 'REQUEST_COACHE_DETAIL',
    SEND_COACHE_DETAIL: 'SEND_COACHE_DETAIL',

    REQUEST_COACHE_CREATE_ROUTE: 'REQUEST_COACHE_CREATE_ROUTE',
    SEND_COACHE_CREATE_ROUTE: 'SEND_COACHE_CREATE_ROUTE',

    CREATE_PASSWORD: 'CREATE_PASSWORD',
    SEND_PASSWORD: 'SEND_PASSWORD',

    SEND_LOADING: 'SEND_LOADING'

};