export const EVENT = {
    GET_EVENTS_LIST: 'GET_EVENTS_LIST',
    SEND_EVENTS_LIST: 'SEND_EVENTS_LIST',

    REQUEST_NEW_EVENT_CREATE: 'REQUEST_NEW_EVENT_CREATE',
    SEND_EVENT_CREATE_SUCCESS: 'SEND_EVENT_CREATE_SUCCESS',

    REQUEST_EVENT_UPDATE: 'REQUEST_EVENT_UPDATE',
    SEND_EVENT_UPDATE_SUCCESS: 'SEND_EVENT_UPDATE_SUCCESS',

    REQUEST_EVENT_DELETE: 'REQUEST_EVENT_DELETE',
    SEND_EVENT_DELETE_SUCCESS: 'SEND_EVENT_DELETE_SUCCESS',

    REQUEST_EVENT_DETAIL: 'REQUEST_EVENT_DETAIL',
    SEND_EVENT_DETAIL: 'SEND_EVENT_DETAIL',

    REQUEST_EVENT_CREATE_ROUTE: 'REQUEST_EVENT_CREATE_ROUTE',
    SEND_EVENT_CREATE_ROUTE: 'SEND_EVENT_CREATE_ROUTE',

    SEND_LOADING: 'SEND_LOADING'

};