export const PROFILE = {

    TEACHER_REQUEST_PROFILE_UPDATE: 'TEACHER_REQUEST_PROFILE_UPDATE',
    TEACHER_SEND_PROFILE_UPDATE_SUCCESS: 'TEACHER_SEND_PROFILE_UPDATE_SUCCESS',

    TEACHER_REQUEST_PROFILE_DETAIL: 'TEACHER_REQUEST_PROFILE_DETAIL',
    TEACHER_SEND_PROFILE_DETAIL: 'TEACHER_SEND_PROFILE_DETAIL',
};