export const CLASS = {
    TEACHER_GET_CLASSES_LIST: 'TEACHER_GET_CLASSES_LIST',
    TEACHER_SEND_CLASSES_LIST: 'TEACHER_SEND_CLASSES_LIST',

    TEACHER_REQUEST_CLASS_STUDENT_ATTENDANCE: 'TEACHER_REQUEST_CLASS_STUDENT_ATTENDANCE',
    TEACHER_SEND_CLASS_STUDENT_ATTENDANCE: 'TEACHER_SEND_CLASS_STUDENT_ATTENDANCE',

    REQUEST_PREV_WEEK_ATTENDANCE: 'REQUEST_PREV_WEEK_ATTENDANCE',
    SEND_PREV_WEEK_ATTENDANCE: 'SEND_PREV_WEEK_ATTENDANCE',
    REQUEST_NEXT_WEEK_ATTENDANCE: 'REQUEST_NEXT_WEEK_ATTENDANCE',
    SEND_NEXT_WEEK_ATTENDANCE: 'SEND_NEXT_WEEK_ATTENDANCE',
    REQUEST_TODAY_ATTENDANCE: 'REQUEST_TODAY_ATTENDANCE',
    SEND_TODAY_ATTENDANCE: 'SEND_TODAY_ATTENDANCE',

    TEACHER_SUBMIT_ATTENDANCE: 'TEACHER_SUBMIT_ATTENDANCE',

    TEACHER_SEND_LOADING: 'TEACHER_SEND_LOADING'

};