export const required = value => (value ? undefined : 'Required');
export const email = value => (value && !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(value) ? 'Invalid email address' : undefined);
export const passwordValidate = (value, allValues) => (value !== allValues.password ? 'Password does not match' : undefined);
export const newPasswordValidator = (value, allValues) => (value !== allValues.new_password ? 'Password does not match' : undefined);
export const oldPasswordValidator = (value, allValues) => ((value && allValues.old_password) && value === allValues.old_password ? 'Current password should not be same as new password' : undefined);
export const onlyLetters = value => (value && !/^[a-zA-Z\s]*$/.test(value) ? 'Only letters allowed' : undefined);
export const onlyNumbers = value => (onlyNumbers && !/^[0-9\s]*$/.test(value) ? 'Only numbers allowed' : undefined);
export const positiveNumbers = value => (value <= 0 ? 'Positive number expected' : undefined);
export const requiredIfRecurringEvent = (value, allValues) => (allValues.isRecurringEvent && !value ? 'Required' : undefined);
export const minimumLength3 = value => (value && value.length < 3 ? 'Minimum length is 3 characters' : undefined);
export const minimumLength2 = value => (value && value.length < 2 ? 'Minimum length is 2 characters' : undefined);
export const minimumLength8 = value => (value && value.length < 8  ? 'Minimum length is 8 characters' : undefined);
export const maximumLength5 = value => (value && value.length > 5 ? 'Maximum length is 5 characters' : undefined);
export const exactLength17 = value => (value && value.length !== 17 ? 'Length must be 17 characters' : undefined);
export const maximumLength15 = value => (value && value.length > 15 ? 'Maximum length is 15 characters' : undefined);
export const maximumLength48 = value => (value && value.length > 48 ? 'Maximum length is 48 characters' : undefined);
export const maximumLength64 = value => (value && value.length > 64 ? 'Maximum length is 64 characters' : undefined);
export const maximumLength128 = value => (value && value.length > 128 ? 'Maximum length is 128 characters' : undefined);
export const maximumLength254 = value => (value && value.length > 254 ? 'Maximum length is 254 characters' : undefined);
export const macAddress = value => (value && !/^[a-fA-F0-9[:-]{17}|[a-fA-F0-9]{12}$/i.test(value) ? 'Invalid MAC address' : undefined);
export const numberValidator = value => (value && !/\d/.test(value) ? 'one upper,one lower, one number and one special character' : undefined);
export const capitalValidator = value => (value && !/[A-Z]/.test(value) ? 'one upper,one lower, one number and one special character' : undefined);
export const lowerValidator = value => (value && !/[a-z]/.test(value) ? 'one upper,one lower,one number and one special character' : undefined);
export const specialValidator = value => (value && !/[!@#$%^&*()_-]/.test(value) ? 'one upper,one lower,one number and one special character' : undefined);
