export const AUTH = {
	SUBMIT_LOGIN_LOADING: 'AUTH_SUBMIT_LOGIN_LOADING',
	SUBMIT_LOGIN: 'AUTH_SUBMIT_LOGIN',
	SUBMIT_LOGIN_SUCCESS: 'AUTH_SUBMIT_LOGIN_SUCCESS',
	LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
	LOGOUT: 'AUTH_LOGOUT',
	IS_LOGGED_IN: 'AUTH_IS_LOGGED_IN',
	SIGN_UP: 'AUTH_SIGN_UP',
	STUDENT_REGISTER: 'STUDENT_REGISTER',
	PARENT_REGISTER: 'PARENT_REGISTER',
	PLAYER_REGISTER: 'PLAYER_REGISTER',
	FORGOT_PASSWORD: 'FORGOT_PASSWORD',
	RESET_PASSWORD: 'RESET_PASSWORD',
	AUTH_FAILED: 'AUTH_FAILED'
};