export const BOOKINGCLASS = {
    GET_BOOKING_CLASSES_LIST: 'GET_BOOKING_CLASSES_LIST',
    SEND_BOOKING_CLASSES_LIST: 'SEND_BOOKING_CLASSES_LIST',

    REQUEST_BOOKING_CLASS_UPDATE: 'REQUEST_BOOKING_CLASS_UPDATE',
    SEND_BOOKING_CLASS_UPDATE_SUCCESS: 'SEND_BOOKING_CLASS_UPDATE_SUCCESS',

    REQUEST_BOOKING_CLASS_DELETE: 'REQUEST_BOOKING_CLASS_DELETE',
    SEND_BOOKING_CLASS_DELETE_SUCCESS: 'SEND_BOOKING_CLASS_DELETE_SUCCESS',

    BOOKING_SEND_LOADING: 'BOOKING_SEND_LOADING'

};