export const KIDEVENT = {
    GET_KIDEVENTS_LIST: 'GET_KIDEVENTS_LIST',
    SEND_KIDEVENTS_LIST: 'SEND_KIDEVENTS_LIST',

    REQUEST_KIDEVENT_DETAIL: 'REQUEST_KIDEVENT_DETAIL',
    SEND_KIDEVENT_DETAIL: 'SEND_KIDEVENT_DETAIL',

    SEND_LOADING: 'SEND_LOADING'

};