export const EVENT = {
    TEACHER_GET_EVENTS_LIST: 'TEACHER_GET_EVENTS_LIST',
    TEACHER_SEND_EVENTS_LIST: 'TEACHER_SEND_EVENTS_LIST',

    TEACHER_REQUEST_EVENT_DETAIL: 'TEACHER_REQUEST_EVENT_DETAIL',
    TEACHER_SEND_EVENT_DETAIL: 'TEACHER_SEND_EVENT_DETAIL',

    TEACHER_SEND_LOADING: 'TEACHER_SEND_LOADING'

};