export const STUDENT = {
    TEACHER_GET_STUDENTS_LIST: 'TEACHER_GET_STUDENTS_LIST',
    TEACHER_SEND_STUDENTS_LIST: 'TEACHER_SEND_STUDENTS_LIST',

    TEACHER_REQUEST_STUDENT_DETAIL: 'TEACHER_REQUEST_STUDENT_DETAIL',
    TEACHER_SEND_STUDENT_DETAIL: 'TEACHER_SEND_STUDENT_DETAIL',

    TEACHER_SEND_LOADING: 'TEACHER_SEND_LOADING'
};